---
- name: 'include OS family specific variables'
  include_vars: '{{ ansible_os_family }}.yml'
  tags: 'osc'

- import_tasks: 'validate.yml'
  tags: 'osc'

- import_tasks: 'packages.yml'
  when: osc__packages_manage
  tags: 'osc'

- import_tasks: 'config.yml'
  tags: 'osc'

- import_tasks: 'zsh.yml'
  tags: 'osc'
