---
- name: 'check .zshrc.d/'
  stat:
    path: '{{ item.home }}/.zshrc.d'
  register: osc__zshrcd_r
  loop_control:
    label: '{{ item.home }}/.zshrc.d'
  loop: '{{ osc__users }}'

- name: 'configure zshrc snippet'
  template:
    dest: '{{ item.invocation.module_args.path }}/osc.zshrc'
    src: 'osc.zshrc.j2'
    owner: '{{ item.item.user }}'
    group: '{{ item.item.group }}'
    mode: 0400
  when: item.stat.exists
  loop_control:
    label: '{{ item.invocation.module_args.path }}/osc.zshrc'
  loop: '{{ osc__zshrcd_r.results }}'
