---
- name: 'Verify'
  hosts: 'all'
  become: true
  tasks:
    - name: 'default role variables - ensure included'
      # ansible-lint: [E505] referenced missing file in
      include_vars: '../../defaults/main.yml'  # noqa 505

    - name: 'OS specific role variables - ensure included'
      include_vars: '../../vars/{{ ansible_os_family }}.yml'
